### ISSUE TITLE
NC Throwback Helmet Logo

### ISSUE THREAD

**Issue by DiddyMack** [cfbrevamped/CFBR-Easy-Installer#102]
The navy outlining of the NC on North Carolina's throwback helmet is supposed to be thicker than it is on their current ones. In the game the outlines look the same, but my apologies if they are not. This isn't a big deal but just a small detail.

It's hard to tell by pictures but it's noticeable on a game broadcast. The navy stripes around the white stripe in the middle of the throwback helmet are thicker and are reflected in the mod.

![image](https://user-images.githubusercontent.com/78277146/106366653-4d716800-630b-11eb-97d7-8c32c06492b1.png)
![image](https://user-images.githubusercontent.com/78277146/106366657-58c49380-630b-11eb-8b4b-e9749dbecb77.png)

**Comment by igloo1** [comment]
added to v9
