### ISSUE TITLE
Installed All- Game does not play. 

### ISSUE THREAD

**Issue by Aaron84ka** [cfbrevamped/CFBR-Easy-Installer#107]
Hello everyone,

I followed the directions to the tee along with watching the youtube video. Everything seems fine and loaded just when I actually go to load the game it seems to be running but just a dark screen. Help please...or ideas?

Thanks!

**Comment by cjveal1** [comment]
did you figure it out? the same thing happens to me

**Comment by Aaron84ka** [comment]
No, I tried to reload A and B then cleaned the disc. The only thing that worked is it loaded somethings on the disc itself. I'm just currently playing the disc version because it did add something's. It added some of the new layout, and lots of new uni's but that is about it. i'm not going to mess with it anymore I'll just wait for the new game to come out. I'm totally excited about that! Sorry I hope you where able to download it properly.

**Comment by igloo1** [comment]
please join our discord for installation issues. Discord.gg/cfbr
