### ISSUE TITLE
Add pride stickers to UNC throwback helmets, move American flag down,  add the state logo beneath, and make ACC logo bigger

### ISSUE THREAD

**Issue by CheechNChong** [cfbrevamped/CFBR-Easy-Installer#112]
![image](https://user-images.githubusercontent.com/73426037/106608199-19c45700-6532-11eb-89d8-e855176b25a3.jpeg)
![image](https://user-images.githubusercontent.com/73426037/106608686-b38c0400-6532-11eb-8043-8b0f2fdda599.jpeg)

**Comment by igloo1** [comment]
thanks for the great feedback and ref pics. Added to v9
