### ISSUE TITLE
Game Crashes While Trying to start dynasty game

### ISSUE THREAD

**Issue by ChazND** [cfbrevamped/CFBR-Easy-Installer#114]
Love the mod! Wondering if this is a common bug? 

Playnow works fine but can't seem to start a game with my existing dynasty files. 

Thanks so much for the mod!!!

**Comment by ChazND** [comment]
v8 btw! issue seems to be on Play Now also..

**Comment by igloo1** [comment]
sounds like an incorrect install. Try redownloading and reinstalling. Please join our discord if you have further issues. Discord.gg/cfbr
