### ISSUE TITLE
Dynasty Crashing

### ISSUE THREAD

**Issue by thunder-thighs** [cfbrevamped/CFBR-Easy-Installer#115]
Using V8 on PS3. I can play an exhibition game fine. Begin a brand new dynasty (with OK State), made a custom schedule to match 2020. I try to play the first game and it freezes at the match up screen. I had FCS East on the schedule. Started another new dynasty and used East Michigan instead with the same result. Haven't yet attempted using a Power 5 school if that matters.

**Comment by igloo1** [comment]
sounds like an incorrect install. Try redownloading and reinstalling. Please join our discord if you have further issues. Discord.gg/cfbr
