### ISSUE TITLE
Missing helmet numbers for Ohio St.

### ISSUE THREAD

**Issue by CheechNChong** [cfbrevamped/CFBR-Easy-Installer#117]
![image](https://user-images.githubusercontent.com/73426037/106814536-8ded2080-6640-11eb-9e2b-9cc777fc7ad6.jpeg)
![image](https://user-images.githubusercontent.com/73426037/106814554-947b9800-6640-11eb-9b11-16247797ab85.jpeg)
![image](https://user-images.githubusercontent.com/73426037/106814568-99d8e280-6640-11eb-9fc0-220037421570.jpeg)

**Comment by igloo1** [comment]
ready to pack in v9
