### ISSUE TITLE
Texas Tech has Texas State uniforms

### ISSUE THREAD

**Issue by demar30** [cfbrevamped/CFBR-Easy-Installer#121]
In rosters, play now, and dynasty mode, Texas Tech's uniforms are replaced with Texas State's uniforms.

**Comment by cfbrevamped** [comment]
Really not sure how this is even possible. Texas Tech never had a DLC pack so it's not likely a DLC issue we overlooked. And We didn't assign any Texas Tech slots to Texas State, so not sure how those jerseys are messed up. Need pictures and more information from you, but this is likely a support issue for Discord, not an actual issue with the mod
