### ISSUE TITLE
New Schools names did not change in my saved dynasty Uniforms and logos show but not the name

### ISSUE THREAD

**Issue by FAMURATTLER** [cfbrevamped/CFBR-Easy-Installer#123]
My dynasty was continued after installing Revamp on PS3. Problem is all new teams still show the old team names, like coastal Carolina has logo and team unis but are still new Mexico, and this goes for the other added teams( Charlotte, Appalachian St., etc) How can I change that.

**Comment by igloo1** [comment]
Correct. Dynasties have their own roster file, so whatever team names were in the roster you started your dynasty with will stay. You can manually edit this in the db editor. Join our discord for help
