### ISSUE TITLE
Michigan Uniforms Color/Bowl Patch Placement

### ISSUE THREAD

**Issue by jackeagle15** [cfbrevamped/CFBR-Easy-Installer#124]
Michigan's new Jordan uniforms look sick, but the blue color used is slightly off from the TC blue that is used for the socks, bicep bands, QB wristbands, etc. From what I understand those items are colored based off the team color selected, so if there's a way to change that to match the uniform color better that would be awesome.

Also I was playing my Michigan dynasty and was in the Natty, when I saw the National Championship patch was placed over top of the Jordan logo on Michigan's jerseys. I was playing Oklahoma and noticed they did not have this issue, as the National Championship patch was placed above their Jordan logo.

Overall I'm loving all the change you guys made, you guys did an amazing job and just wanna say thank you for doing this for us all.

**Comment by igloo1** [comment]
bowl patch placement updated in v9. Team Color is a roster issue and will likely be addressed in the 2021-2022 roster
