### ISSUE TITLE
Louisiana Rajin Cajuns Jersey's and Stadium

### ISSUE THREAD

**Issue by louielennon** [cfbrevamped/CFBR-Easy-Installer#125]
The whole aspect Louisiana Rajin Cajuns need to be updated. Their stadium has since upgraded and jerseys and they no longer go by Louisiana Lafayette anymore but just Louisiana.

**Comment by cfbrevamped** [comment]
This is not an issue. The Sun Belt hasn't been done yet. We know this seems odd since some SBC teams have been updated, but our big SBC update hasn't happened yet
