### ISSUE TITLE
Iowa alternate helmets are actually Maryland helmets

### ISSUE THREAD

**Issue by weest94** [cfbrevamped/CFBR-Easy-Installer#130]

**Comment by igloo1** [comment]
What system are you on? Your patch didn't install properly

**Comment by weest94** [comment]
Ps3

**Comment by cfbrevamped** [comment]
Your patch isn't being applied likely due to faulty download or you incorrectly naming your game folder. Please use [Discord](http://discord.gg/cfbr) for support.
