### ISSUE TITLE
Bug with new V9

### ISSUE THREAD

**Issue by bearsotool** [cfbrevamped/CFBR-Easy-Installer#136]
Downloaded it and hopped onto an exhibition match between Iowa and Iowa State and both teams have alternate helmets that glitch out. Iowa States glitches and looks like Baylor’s helmet and Iowa’s glitches out and looks like Maryland’s.

**Comment by igloo1** [comment]
Sounds like an incorrect install. Please join our discord for help. Discord.gg/cfbr
