### ISSUE TITLE
PS3 V9 files have wrong uniform colors and logos are off

### ISSUE THREAD

**Issue by tronsorm** [cfbrevamped/CFBR-Easy-Installer#141]
Hello,

I just downloaded the V9 files and my game has many weird uniform glitches. For example, the Michigan facemasks are grey, Notre Dame's helmets are only the Shamrock ones, Ohio State's black jerseys have Northwestern's helmets, etc. also Charlotte University's logo is for UConn...

Did I do something wrong in the download process? I would ask this on discord but it would not let me join for some reason....

**Comment by igloo1** [comment]
sounds like an incorrect install. Are you on PS3? If you can, try and join our discord again at discord.gg/cfbr

**Comment by tronsorm** [comment]
I restarted the game and everything was good after the restart...
