### ISSUE TITLE
Virginia Home Game Crash

### ISSUE THREAD

**Issue by bigb43** [cfbrevamped/CFBR-Easy-Installer#144]
When I play with Virginia at Virginia, the game crashes every time as I get ready to kickoff or receive the ball. Is this a known bug in v9?

**Comment by igloo1** [comment]
What system? Sounds like something is corrupted with your game files

**Comment by bigb43** [comment]
OG giant ps3

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by igloo1** [comment]
just tested on mine. Same console w/ v10 installed, no problems. Would recommend installing v10, if that doesn't fix it then clean your disc and re-dump it. If you are PSN version, make sure you enable hen. If the issue persists, stop by our discord and we will help troubleshoot. Discord.gg/cfbr

**Comment by bigb43** [comment]
Thank you much!
________________________________
