### ISSUE TITLE
Intro Crash RPCS3

### ISSUE THREAD

**Issue by Ben-Jax999** [cfbrevamped/CFBR-Easy-Installer#147]
As soon as the game opens the screen is completely black and one second of the intro theme plays and then everything stops and the game freezes and crashes... I've restarted my computer and restarted RPCS3 and nothing is working. I don't know if my antivirus deleted a file(that's happened before) or if an RPCS3 update just broke it.

**Comment by igloo1** [comment]
Would sound like a file is missing. Join our discord if you have further issues discord.gg/cfbr
