### ISSUE TITLE
Costal Carolina Unis and logo

### ISSUE THREAD

**Issue by Gethynator** [cfbrevamped/CFBR-Easy-Installer#151]
Coastal Carolina unis and logo have been replaced with new Mexico state logo and unis. please fix if possible. 
![Screenshot (19)](https://user-images.githubusercontent.com/80916645/111673750-aa5cab00-87f1-11eb-8000-01b97d2dfe16.png)

**Comment by bread-in** [comment]
I'm getting the same issue. It also affects App State and Charlotte.

**Comment by igloo1** [comment]
Download the latest roster from operation sports. https://forums.operationsports.com/forums/ncaa-football-rosters/964552-ncaa-football-14-2020-2021-roster-update.html
