### ISSUE TITLE
South Carolina home garnet jersey

### ISSUE THREAD

**Issue by BullWard** [cfbrevamped/CFBR-Easy-Installer#152]
Just started playing revamped for the first time, picked South Carolina's home garnet jersey and noticed not all but some of the players have missing shoulder sleeve striping.  
![IMG_1364](https://user-images.githubusercontent.com/81064238/111893974-30891500-89dd-11eb-8caa-3b6efdcf8edc.jpg)

**Comment by igloo1** [comment]
This was done intentionally. Shouldn't be an issue going forward since recruits are automatically generated with tight sleeves
