### ISSUE TITLE
Update Maryland Gloves Options 

### ISSUE THREAD

**Issue by EazyMani** [cfbrevamped/CFBR-Easy-Installer#154]
On the uniform settings Maryland only has default gloves. 

![C5678A11-EBCB-49FB-8E08-32F75B2F5AA4](https://user-images.githubusercontent.com/81488306/112732959-885ed900-8f13-11eb-97d5-a2a1982a57c2.jpeg)
![74060C87-43D3-4A71-BF1F-BCBA9D9E1812](https://user-images.githubusercontent.com/81488306/112732961-88f76f80-8f13-11eb-95df-6b9ea239bac9.jpeg)
![E085B008-2B74-4A2F-95CC-A9E1A19D7B4A](https://user-images.githubusercontent.com/81488306/112732962-88f76f80-8f13-11eb-96bc-07b12f973260.jpeg)
![1F711F66-97A4-467D-A5AF-0B2679F61F1B](https://user-images.githubusercontent.com/81488306/112732963-89900600-8f13-11eb-91a2-9fc8f3820ad6.jpeg)

**Comment by igloo1** [comment]
Default gloves are team color. V11 adds white and black gloves as well
