### ISSUE TITLE
Tennessee's Smoke Gray Helmet

### ISSUE THREAD

**Issue by BullWard** [cfbrevamped/CFBR-Easy-Installer#161]
Don't know if this has been posted before, I just noticed Tennessee's Smoke Gray helmet is an old Miss State helmet currently in the game.  
![Tennessee](https://user-images.githubusercontent.com/81064238/113299327-c1f46300-92ca-11eb-8daf-5f4de641b27b.jpg)

**Comment by igloo1** [comment]
try reinstalling part B. Join our discord for further assistance (discord.gg/cfbr)
