### ISSUE TITLE
PS3 Disc version V10 - Iowa State helmet missing

### ISSUE THREAD

**Issue by olbleedyeyes** [cfbrevamped/CFBR-Easy-Installer#162]
Playing PS3 disc with the new update and the white helmets are missing for Iowa State. in place is a gold Baylor helmet. I think it was the default baylor helmet from the base game. 

All the other Iowa State parts are there outside of the white helmet, i believe

EDIT: Two of Iowa's alternate helmets are messed up as well.

**Comment by igloo1** [comment]
Try reinstall part B. Join our discord for further assistance (discord.gg/cfbr)
