### ISSUE TITLE
Auburn pants need orange stripe to be thicker 

### ISSUE THREAD

**Issue by cfbrevamped** [cfbrevamped/CFBR-Easy-Installer#2]
reference image from 2019-2020 seasom:

![pants stripe](https://auburntigers.com/s3/auburntigers.com/custompages/gallery/fb_georgia_111619/thumbs/_big_DSC_3327.jpg)

**Comment by igloo1** [comment]
Done. Ready to pack

**Comment by cfbrevamped** [comment]
Packed, waiting for release to close

**Comment by cfbrevamped** [comment]
Fixed in ACC Pack (V3)
