### ISSUE TITLE
South Carolina black helmet stripe

### ISSUE THREAD

**Issue by igloo1** [cfbrevamped/CFBR-Easy-Installer#20]
Need space between outer and inner stripes like white helmet.![image](https://user-images.githubusercontent.com/69478322/95671847-2a4e5d00-0b50-11eb-83a4-7c425e1dc253.jpeg)

**Comment by igloo1** [comment]
Make white helmet chinstrap and guard black too

**Comment by igloo1** [comment]
Fixed and released in v4.2 booster preview

**Comment by cfbrevamped** [comment]
Fixed in V4.2 release
