### ISSUE TITLE
Virginia Tech maroon helmet facemask

### ISSUE THREAD

**Issue by wash437** [cfbrevamped/CFBR-Easy-Installer#22]
VTech face masks on maroon helmets should be maroon not white. 

Thank you, I appreciate all that you do.

**Comment by cfbrevamped** [comment]
Did you mean to close this issue?

**Comment by wash437** [comment]
No sir I didn’t

**Comment by wash437** [comment]
No sir

**Comment by cfbrevamped** [comment]
Fixed with V5
