### ISSUE TITLE
Bc Home unis back numbers X axis

### ISSUE THREAD

**Issue by igloo1** [cfbrevamped/CFBR-Easy-Installer#25]
![FF3A6AFB-5CFF-4AA2-B462-A50374834EDB](https://user-images.githubusercontent.com/69478322/96200914-1455e900-0f10-11eb-8087-90b2ebba9708.jpeg)

**Comment by igloo1** [comment]
Corrected in XBOX update. Numbers also fixed. Need to pack for PS3

**Comment by cfbrevamped** [comment]
Fixed in V5
