### ISSUE TITLE
College Football Revamped isn't installing fully

### ISSUE THREAD

**Issue by Nateydog** [cfbrevamped/CFBR-Easy-Installer#276]
I have followed tutorials step by step, gotten the game on the emulator, and gotten it "revamped." But when I go into the game, I got the roster downloaded & some other stuff is correct. However, it's still the old look of NCAA 14. The Uniforms haven't changed, The Teams are the same, and teams like Appalachian State is Idaho. Dynasty is still the old version with the same schedule as the 2013 season, and the Conferences are the same as back in 2013. 

I just want to know what I could've done wrong because I've tried over & over again to fix this issue.

**Comment by jwlewis2** [comment]
what did you do to fix this having the same issue

**Comment by MBGB1728** [comment]
Ditto
