### ISSUE TITLE
Clemson Purple Jersey ACC patch fix

### ISSUE THREAD

**Issue by CheechNChong** [cfbrevamped/CFBR-Easy-Installer#28]
Just a color swap of “ACC” and the line underneath. 
![1E32EBBD-AFE6-4D93-9007-94CE1C85B236](https://user-images.githubusercontent.com/73426037/97105604-822dad80-1692-11eb-81ee-5cc75a27933e.jpeg)
![AED1EEBF-4FAD-4680-8FF7-B4A63E31B655](https://user-images.githubusercontent.com/73426037/97105605-835eda80-1692-11eb-9a58-0d322928b675.jpeg)

**Comment by igloo1** [comment]
fixed and ready to pack

**Comment by cfbrevamped** [comment]
Fixed with V5
