### ISSUE TITLE
FSU team color accessories/White Gloves

### ISSUE THREAD

**Issue by wutang21** [cfbrevamped/CFBR-Easy-Installer#29]
FSU’s team color accessories do not match the modded uniforms. The accessories are too bright much like the face mask that was fixed in V4. Also FSU doesn’t have the alternate white Nike gloves that some of the other teams have been modded with.

**Comment by RLane22** [comment]
Why do you expect Florida State to just get gloves

**Comment by wutang21** [comment]
It’s not that I expect it, but I see that the majority of the teams that
have been updated have 2-3 sets of gloves. Other teams that are in future
plans have been forecasted with multiple pair of gloves. FSU has the one
Garnet pair and no others. I was just curious if that might have been
possibly missed.

**Comment by cfbrevamped** [comment]
Github isn't for requests. If there's a legitimate issue with the FSU colors please reopen this with a new issue and some screenshots to show what you mean
