### ISSUE TITLE
Random crashing with certain uniforms on XBOX version of V2 installer

### ISSUE THREAD

**Issue by cfbrevamped** [cfbrevamped/CFBR-Easy-Installer#3]
Not known if this is caused by helmets, jerseys or fields. Crashes when loading ingame. Currently investigating

**Comment by co510** [comment]
On Xbox console I started a Play Now game between Texas A&M visiting UGA.  Aggies had standard road jerseys, Bulldogs were wearing ALT#1 jersey.    Game crashed twice w this setup during the runout video.  Started same matchup with Bulldogs wearing their standard home jersey and the game loaded fine.
