### ISSUE TITLE
Bama Goal Pads

### ISSUE THREAD

**Issue by CheechNChong** [cfbrevamped/CFBR-Easy-Installer#31]
Update Alabama goal pad font to match real life version seen in photo. 
![E55BDEBF-F350-4181-AB3E-BEF1396CBD33](https://user-images.githubusercontent.com/73426037/97818224-52247280-1c6f-11eb-8f21-f9e4f076361e.jpeg)

**Comment by cfbrevamped** [comment]
Fixed with V5
