### ISSUE TITLE
Crashing Issues while playing games

### ISSUE THREAD

**Issue by 3456matt** [cfbrevamped/CFBR-Easy-Installer#32]
On the PC disc version I am getting crashes half way through games and sometimes in Super Sim. The screen will just freeze and close out. I have the v4.0 downloaded with the hot fix installed. I have played the games on previous versions and never had a problem except the crashing that you guys were already aware of. Thank you.

**Comment by igloo1** [comment]
Crashes in super sim is one I have never heard of. As far as I know, we wouldn't have done anything to impact that.

Where exactly are you getting freezes in-game?

**Comment by 3456matt** [comment]
It might just be a personal error when installing the mods or my PC, but I would get through halftime and about mid way through the 3rd quarter and the game would crash and that would happen in both supersim and if I played the game. This happened to me every time I went in game for Dynasty Mode and about a 1/4 of the time in regular exhibition games.

**Comment by 3456matt** [comment]
All is fixed, great job guys.
