### ISSUE TITLE
Toledo has Texas A&M gloves

### ISSUE THREAD

**Issue by gprep93** [cfbrevamped/CFBR-Easy-Installer#36]

**Comment by RLane22** [comment]
Dude they’ve literally said over and over again that G5’s will have different gloves until they get to them. Wtf

**Comment by gprep93** [comment]
Dude, excuse me for being new and not having seen that, asshole

**Comment by RLane22** [comment]
Could’ve taken time to search...

**Comment by gprep93** [comment]
You're right, I could and should have.  Doesn't mean you needed to be a dick about it.

**Comment by igloo1** [comment]
Closing this for now
