### ISSUE TITLE
Bowl Patches drawn in incorrect spots on new jerseys

### ISSUE THREAD

**Issue by cfbrevamped** [cfbrevamped/CFBR-Easy-Installer#5]
Examlple

![example](https://i.imgur.com/jHGEdqT.jpg)

**Comment by igloo1** [comment]
Controlled by `decalUV` in mixmatch. Assume it follows the same x, y, scaleX, scaleY format as v4 RSF values

**Comment by cfbrevamped** [comment]
Packed, waiting on release to close

**Comment by cfbrevamped** [comment]
Fixed in ACC Pack (V3)
