### ISSUE TITLE
Clemson goal pads

### ISSUE THREAD

**Issue by CheechNChong** [cfbrevamped/CFBR-Easy-Installer#50]
Small fix. Just make the line purple on the ACC logo instead of grey. ![image](https://user-images.githubusercontent.com/73426037/102724466-af3abd00-42dd-11eb-900d-d3c743d649c1.jpeg)![image](https://user-images.githubusercontent.com/73426037/102724469-b5309e00-42dd-11eb-9a27-9f67d17c8cb2.jpeg)

**Comment by cfbrevamped** [comment]
fixed with v8
