### ISSUE TITLE
Unable to download cfbr-easy-intaller v6

### ISSUE THREAD

**Issue by havmatic1** [cfbrevamped/CFBR-Easy-Installer#53]
Trying to download v6 and once finished downloading error comes up telling me file is missing or damage

**Comment by RLane22** [comment]
Just downloaded it this morning. Works fine

**Comment by havmatic1** [comment]
yeah I'm unable to open it still giving me a error telling me file unable to format

**Comment by havmatic1** [comment]
I think it might work i'm trying it on my mac right now I'll keep you update

**Comment by havmatic1** [comment]
@RLane22  finally got it fixed
