### ISSUE TITLE
Base OU helmet with wrong logo???

### ISSUE THREAD

**Issue by SoonerMan1** [cfbrevamped/CFBR-Easy-Installer#55]
Not sure if this is an isolated issue, but the base crimson helmets for the Sooners still feature the old narrow interlocking OU instead of the new larger OU. The color is also off a bit and the base crimson helmet needs more shine. Spoke with the guys on discord and WaddWadd provided screenshots showing it is okay at least on his system. I’m running a PS3 version so who knows. Here’s some pictures of the real life helmets and I’ll jump back on the game tomorrow morning and get pics of what I’m seeing in game. Just for reference, the last picture is similar to what I see in game. 
![5BED685B-9DDF-44B6-AB32-4C82C927167E](https://user-images.githubusercontent.com/76726902/103270229-0b0be280-497d-11eb-8edc-c2b5be00dca1.jpeg)

![D2FC935A-DAD1-4560-AB9F-A8B6F5BE8017](https://user-images.githubusercontent.com/76726902/103270285-1d861c00-497d-11eb-8092-52149cd741d3.jpeg)
![22D5DCBD-BE46-4363-B2C5-5E39A4C5E8CC](https://user-images.githubusercontent.com/76726902/103270307-2ecf2880-497d-11eb-917a-8e69e104f44a.jpeg)

**Comment by SoonerMan1** [comment]
Here’s an in game picture I took for reference. 
![DB035EB3-352C-49B2-8B34-AB97E05635B3](https://user-images.githubusercontent.com/76726902/103301192-6f06c900-49c6-11eb-8e76-4e03f3f97eda.jpeg)

**Comment by igloo1** [comment]
Solved as incorrect install
