### ISSUE TITLE
S Car Wrong logo

### ISSUE THREAD

**Issue by okgogo3** [cfbrevamped/CFBR-Easy-Installer#56]
The logo for south carolina have the white outline like on the black helmets instead of the garnet outline ![image](https://user-images.githubusercontent.com/72984488/103292826-9d7fa680-49bc-11eb-9568-5df689c7f775.jpeg) 

![image](https://user-images.githubusercontent.com/72984488/103292831-a07a9700-49bc-11eb-9cc0-999001209b79.jpeg)

![image](https://user-images.githubusercontent.com/72984488/103292836-a2dcf100-49bc-11eb-90ff-562eb2239196.jpeg)

![image](https://user-images.githubusercontent.com/72984488/103425959-06654b00-4b84-11eb-99a6-56a0a2864913.jpeg)

**Comment by igloo1** [comment]
fixed in v9
