### ISSUE TITLE
Florida GATOR Field Endzone/redzone Outline

### ISSUE THREAD

**Issue by coachgunns** [cfbrevamped/CFBR-Easy-Installer#57]
I know its something minor but can we get the BLUE out line for the RED ZONE- ENDZONE. They use the Outline no matter what. Opposite the end zone color. Please and Thank you.
![Capture1](https://user-images.githubusercontent.com/76753989/103316284-dd568600-49dc-11eb-9d2d-bee32e30b083.PNG)
![capture2](https://user-images.githubusercontent.com/76753989/103316290-e34c6700-49dc-11eb-9790-4fcc80145914.jpg)
![Capture3](https://user-images.githubusercontent.com/76753989/103316293-e5aec100-49dc-11eb-91fc-0ec7dcc03a65.PNG)

**Comment by chad-walk** [comment]
updated and ready to be included in v8

**Comment by cfbrevamped** [comment]
Fixed with v8
