### ISSUE TITLE
Texas at Iowa State Dynasty Mode freeze

### ISSUE THREAD

**Issue by olbleedyeyes** [cfbrevamped/CFBR-Easy-Installer#58]
Playing as Iowa State in Dynasty Mode. Had Texas visiting Iowa State in week 6 and the game froze on the opening scenes. Texas was wearing it's standard away unis and I had ISU in their all black. 

I just loaded the game up again and did the same uniform combo, and so far no issue. So it might have just been a one off thing.

**Comment by cfbrevamped** [comment]
Closing this as v7.1 has fixed most stability issues. Reopen if you are still having issues with more detail
