### ISSUE TITLE
Auburn helmet stripe needs to be brushed in PS

### ISSUE THREAD

**Issue by igloo1** [cfbrevamped/CFBR-Easy-Installer#6]
White stripe down the middle of the orange stripe. Brush it in PS to fill

**Comment by igloo1** [comment]
Updated and sent to d wade. Ready to pack

**Comment by cfbrevamped** [comment]
Packed, waiting for release to close

**Comment by cfbrevamped** [comment]
Fixed in ACC Pack (V3)
