### ISSUE TITLE
Dynasty Freezing 

### ISSUE THREAD

**Issue by gocalebs** [cfbrevamped/CFBR-Easy-Installer#63]
Virginia Tech can’t play Georgia Southern at Virginia Tech, the game freezes. The band also for some reason spells out LSU on the field

**Comment by cfbrevamped** [comment]
What version were you on, and send pictures of where you were freezing

**Comment by cfbrevamped** [comment]
Closing this as there was no response in the last two weeks and v7.1 should have fixed all crashing issues related to the mod
