### ISSUE TITLE
Dynasty Crashing and loading in an Exhibition game crashing. 

### ISSUE THREAD

**Issue by jrgouker2** [cfbrevamped/CFBR-Easy-Installer#64]
I don’t know how to fix this. I tried reinstalling the mod and that didn’t work either

**Comment by dlewis0990** [comment]
I'm having the exact same issue right now

**Comment by Holdeenoe** [comment]
Has anyone figured out how to fix this issue?

**Comment by jrgouker2** [comment]
I uninstalled the copy of the game and reinstalled the mod to my usb drive
and recopied the game and reinstalled the mod and that worked for me

**Comment by dlewis0990** [comment]
Yea. One of the two files got corrupted while downloading so I had to erase the ones from my USB, re-download and installs

**Comment by igloo1** [comment]
Closing this as it was an incorrect install. Please join our discord for support discord.gg/cfbr
