### ISSUE TITLE
Xbox 360 Dynasty Crashes When Viewing Graphics/Cut Scenes In Game

### ISSUE THREAD

**Issue by DubbedXR** [cfbrevamped/CFBR-Easy-Installer#66]
You have to SpamSkip every Graphic (PreGame, Studio Updates, Halftime Show, Endgame, or it will freeze your console or bring it back to dashboard.

**Comment by cfbrevamped** [comment]
Should be fixed as of 7.1 update. If you continue to have issues with 7.1+ then re-open
