### ISSUE TITLE
Issues with the Texas A&M 1998 Throwback Helmets

### ISSUE THREAD

**Issue by realmccoy09** [cfbrevamped/CFBR-Easy-Installer#67]
The aTm logo shown in the pictures is not the correct one. For these helmets, they actually went back to the old 1998 aTm logo where the T is significantly larger than the A&M, and the A&M are smaller and inset to the T, unlike the current helmet logo where they are centered on the serifs of the T. Please see the pictures 

https://bloximages.chicago2.vip.townnews.com/myaggienation.com/content/tncms/assets/v3/editorial/0/ff/0ff59f80-c5df-11e8-b3d1-8f9656842077/5bb2c40718b48.image.jpg?resize=1200%2C900

https://bloximages.chicago2.vip.townnews.com/myaggienation.com/content/tncms/assets/v3/editorial/0/8b/08b515e8-c5df-11e8-ad9a-33b1d81b9473/5bb2c3fae4224.image.jpg?resize=1200%2C900

The one you have pictured on instagram is not this logo, its the current logo on the helmets, and I believe the sizing of the ATM decal on that helmet may be a bit smaller than it should be as well, normally the decal goes from just over the facemask all the way to the back vent on the riddell speed helmets

**Comment by cfbrevamped** [comment]
We won't be assigning a helmet slot specifically for the throwback helmet unless we are able to have unlimited helmet slots in the game, which is not possible at the moment. While it's not 100% accurate, it would be unreasonable to assign a second helmet slot for such a minor tweak when we are so limited on the total number of helmets

**Comment by realmccoy09** [comment]
It’s part of the 98 throwback uniform you have already shown on your pictures, the helmet logo just needs to be adjusted. Y’all are priding yourselves on accuracy, I’m just pointing out where it needs adjustments, not a whole new helmet. 

Matthew R. McCoy
(432) 559-6346

On Jan 15, 2021, at 4:15 PM, College Football Revamped Mod <notifications@github.com> wrote:

﻿
We won't be assigning a helmet slot specifically for the throwback helmet unless we are able to have unlimited helmet slots in the game, which is not possible at the moment. While it's not 100% accurate, it would be unreasonable to assign a second helmet slot for such a minor tweak when we are so limited on the total number of helmets
