### ISSUE TITLE
UNC Jerseys

### ISSUE THREAD

**Issue by heelshouse** [cfbrevamped/CFBR-Easy-Installer#72]
The helmets are updated, but the jerseys themselves are our 2010-era uniforms, instead of the updated argyle ones we currently wear. 

Additionally, we use our white helmet very frequently but only the blue one is in the game. Would really appreciate a refresher there!

**Comment by igloo1** [comment]
Sounds like an incorrect install. Please join our discord (discord.gg/cfbr) for support
