### ISSUE TITLE
Blank Grey Uniforms/Game Freezing

### ISSUE THREAD

**Issue by dlewis0990** [cfbrevamped/CFBR-Easy-Installer#74]
So this is on PS3, digital download from playstation store edition....when going to change uniforms, it just says custom and everything is blank and Grey. Then if I try and start a game, the playstation freezes completely. #

**Comment by jrgouker2** [comment]
I uninstalled the copy of the game and reinstalled the mod to my usb drive
and recopied the game and reinstalled the mod and that worked for me

**Comment by cfbrevamped** [comment]
Wipe your USB, redownload the mod file(s) and reinstall. This is an issue with your internet/download being corrupted or interrupted, not the mod itself
