### ISSUE TITLE
Gators orange jerseys

### ISSUE THREAD

**Issue by gluckmaster15** [cfbrevamped/CFBR-Easy-Installer#79]
For certain players the white and blue stripes don't appear on the shoulders of the orange jerseys. #47 and #68 were most noticeable on the field. Was using blue helmet, orange jersey, and blue pants as the combo if that matters.

**Comment by cfbrevamped** [comment]
We will not be adding stripes to long sleeve jerseys due to warping and the fact that they look ugly, we will be removing those sleeves from the game altogether shortly so everyone has tight sleeves
