### ISSUE TITLE
Windows Defender flagging qkl_misc.ast as a Trojan

### ISSUE THREAD

**Issue by SnakeEyes187** [cfbrevamped/CFBR-Easy-Installer#81]
just happened for the first time this morning. several others in the Discord seeing it as well. 

RPCS3 (latest)
disc version
CFR 7.1

**Comment by RLane22** [comment]
Trojan condom?

**Comment by cfbrevamped** [comment]
This is 100% a false positive. You can check the file at [virustotal](https://www.virustotal.com/gui/file/fc8ddb1e6a75e514ac15ef70fde9d701141e377df64478bb96b31c778d4d415f/detection), not sure what is causing this but we will try to repack the files for V8 and hope it doesn't get flagged:
