### ISSUE TITLE
Online User OSDK ?

### ISSUE THREAD

**Issue by FrankieWL** [cfbrevamped/CFBR-Easy-Installer#85]
Thank you for providing this opportunity to play this game. It’s been seven years for me. However, when “start game” button is pressed on intro screen the online account OSDK automatically loads and then becomes automatically disabled. This also happens when I try to go to online mode and roster share, and then it kicks me back out to the main menu screen.  I can’t play online or upload updated rosters because of this. Also the game freezes when loading an exhibition game and when I go to edit rosters (probably because there are no rosters). Please help.

**Comment by igloo1** [comment]
Sounds like an incorrect install. The mod doesn't cause issues when playing online

Please join our discord for support discord.gg/cfbr

**Comment by FrankieWL** [comment]
I reinstalled and it works now.  Thanks again for all the effort put into
creating this opportunity to keep this game alive.
