### ISSUE TITLE
National championship/ bowl patches

### ISSUE THREAD

**Issue by SoonerMan1** [cfbrevamped/CFBR-Easy-Installer#86]
The patches for the national championship/ bowls (Not sure about other bowls because I've only been in the national title) on the OU uniforms need to be repositioned so they don't awkwardly cover the big 12 logo. This also applies to the big 12 championship patch. Should be left shoulder even though they don't wear one in championship games in real life(looks good in game) I might suggest placing bowl/ championship patches for big 12 on the left shoulder above the jumpman. Included one of Florida first reference of other Jordan unis. Photos for reference of issue are below. ![image](https://user-images.githubusercontent.com/76726902/104412801-a632b980-5532-11eb-88dd-b9ceba27e3f2.jpeg)![image](https://user-images.githubusercontent.com/76726902/104412823-b77bc600-5532-11eb-9daf-ebfda801fbf0.jpeg)![image](https://user-images.githubusercontent.com/76726902/104412833-bc407a00-5532-11eb-95a5-0e3c466df83b.png)

**Comment by igloo1** [comment]
We forgot to update positioning in v6. Updated in v8
