### ISSUE TITLE
Freezing when opening Dynasty or RTG save

### ISSUE THREAD

**Issue by Ben-Jax999** [cfbrevamped/CFBR-Easy-Installer#88]
The game works fine opening up and getting to the main screen, but as soon as I get into the dynasty menu and click one of my saves the game freezes

**Comment by seabii** [comment]
same here

**Comment by seabii** [comment]
it freezes when i try to go into exhibition too

**Comment by comstock2005** [comment]
Latest update for RPCS3 crashed the game. Can't load rosters or dynasties. Can't play exhibition games either. Don't know if they are working on a fix or not.

**Comment by Ben-Jax999** [comment]
> Latest update for RPCS3 crashed the game. Can't load rosters or dynasties. Can't play exhibition games either. Don't know if they are working on a fix or not.

good to know it's not me then :)

**Comment by comstock2005** [comment]
https://rpcs3.net/compatibility?b&o=1d

Revert back to 0.0.14-11568. Just copy and paste the rpcs3.exe from that downloaded 7z file to where your current folder for RPCS3 is.

**Comment by comstock2005** [comment]
Nevermind... You'll need all of the files from that 7z. replace all of them.

**Comment by comstock2005** [comment]
https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-52deff06baf6523d7d39bf022f08caf0beeb1853/rpcs3-v0.0.14-11537-52deff06_win64.7z

Revert back to that version and it works. You'll have to start all over with the pkg files though.

**Comment by comstock2005** [comment]
http://dus01.ps3.update.playstation.net/update/ps3/image/us/2020_1203_03373a581934f0d2b796156d2fb28b39/PS3UPDAT.PUP

That's the latest firmware.

**Comment by comstock2005** [comment]
https://www.mediafire.com/file/x1on41b5new69rs/PS3UPDAT.pkg/file

Version 01.02 NCAA Football 14 pkg

**Comment by comstock2005** [comment]
https://www.mediafire.com/file/ke6gz32nk5bkjfq/PS3UPDAT.PUP/file

This firmware should download faster than the PlayStation website.

**Comment by comstock2005** [comment]
dev_hdd0\disc\BLUS31159-[NCAA Football 14]\PS3_GAME\USRDIR\qkl_misc.ast

Make sure this file didn't get deleted by your virus protection.

**Comment by ProteanPlatypus** [comment]
I was having this problem too, where starting any exhibition match or loading an RTG save caused the emulation to freeze. Reinstating qkl_mist.ast fixed this. (Windows Security had quarantined the file.)

dev_hdd0\disc\BLUS31159-[NCAA Football 14]\PS3_GAME\USRDIR\qkl_misc.ast

**Comment by cfbrevamped** [comment]
Closing this since it's not a mod issue. Not sure why Windows antivirus is flagging the file as malicious (it is obviously not a virus). V8 should fix this regardless

**Comment by MrStallion15** [comment]
i have same problem when i load into any game it freezes on loading screen i have an emulator.
