### ISSUE TITLE
No changes after update.

### ISSUE THREAD

**Issue by Issik1** [cfbrevamped/CFBR-Easy-Installer#93]
Followed all the instructions, everything looked like it updated smoothly. Opened the game and there’s no visible changes to the game. Granted I’m not a tech guy so I could’ve have easily messed up with the steps perhaps.

**Comment by 39p** [comment]
I have the same problem, no changes and it's seem to be the normal one

**Comment by Issik1** [comment]
I did on my slim first and then after never getting it to switch I did it on the fat and got it first try. Follow the steps and make sure that the updates both a&b match why kind of game you have. So if you have the disc make sure the update title says disc and not psn

Alex Issik
587-433-2539
issik@hotmail.co.uk

On Jan 21, 2021, at 8:42 PM, 39p <notifications@github.com> wrote:

﻿

I have the same problem, no changes and it's seem to be the normal one

**Comment by igloo1** [comment]
Please join our discord for support discord.gg/cfbr
