### ISSUE TITLE
Satin finish on Red ALT OU helmet.

### ISSUE THREAD

**Issue by SoonerMan1** [cfbrevamped/CFBR-Easy-Installer#95]
In game red alternate helmets would look more accurate with that Satin Finish youre using for Minnesota. ![image](https://user-images.githubusercontent.com/76726902/105559488-ec2c1200-5cd6-11eb-9782-dccab16efd80.jpeg)

**Comment by igloo1** [comment]
not sure I agree with this one

**Comment by SoonerMan1** [comment]
Would be worth a shot just to see how it looks on your end first. They don't come across fully matte in game, sometimes look a bit glossy. Real life they are matte/satin. I've held a real one in my hands at a pregame event so I can attest to them having no gloss unlike the white helmets.
