### ISSUE TITLE
UVA jersey logo

### ISSUE THREAD

**Issue by e2601** [cfbrevamped/CFBR-Easy-Installer#98]
Just a very minor thing, but I noticed the collar logo on UVA's orange jersey is wrong. Should be the new alternate logo
![121108066_350399139618480_368375025488865796_n](https://user-images.githubusercontent.com/73268168/105775861-8ab5ae80-5f35-11eb-9eb8-fea7901142fc.jpg)

**Comment by igloo1** [comment]
You are correct. We will add this to a future update. Thanks

**Comment by igloo1** [comment]
updated and ready to be packed
